name: Optimize Fonts

on:
  push:
    branches: [main]
    paths:
      - 'scripts/optimize-fonts.mjs'
  workflow_dispatch:

jobs:
  optimize-fonts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Optimize fonts
        run: npm run optimize-fonts

      - name: Commit optimized fonts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update optimized fonts'
          file_pattern: 'public/fonts/*'
